# Generated by Django 3.2.13 on 2022-05-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetInTouch',
            new_name='Contact',
        ),
    ]
